language: cpp

sudo: required

dist: trusty

compiler:
  - g++

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then source include/pkglist.Ubuntu-14.04; sudo apt-get -y install ${BASE_PKGS} ${COMPILER_PKGS} ${GOOGLE_PKGS} ${BOOST_PKGS} ${MISC_PKGS} ${HDFS_PKGS} lcov ruby-dev ; fi
  - gem install coveralls-lcov

before_script: cmake -Bbuild -H. -DDEBUG=ON -DCOVERAGE=ON -DCMAKE_CXX_COMPILER=$COMPILER ; cd build

script:
  - make -j4
  - ctest --verbose

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' '/home/travis/build/camsas/firmament/build/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

branches:
  only:
    - master

notifications:
  email: true
    - firmament-dev@camsas.org

os:
  - linux
